name: Update GPU Prices

on:
  schedule:
    - cron: "0 * * * *"   # 每小时第0分钟跑一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
      - name: Build latest prices
        run: |
          python scripts/fetch_sources.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/prices.json || true
          git add site/data/prices.json || true
          git commit -m "chore: update prices.json [skip ci]" || echo "No changes"
          git push
